spring.application.name=Ex16Security01


# 오라클 CE버전 - 8080포트가 기본이라서 포트 충돌이 남. 포트 회피.
# server.port=8090

# thymeleaf
spring.thymeleaf.cache=false

# security
# default username / password
spring.security.user.name=user
spring.security.user.password=1234


# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
# SQL 콘솔로그 2번 찍히는 것 방지 : false로 설정
spring.jpa.show-sql=false

# 사용할 데이터베이스의 방언(Dialect) 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# pretty sql format - 줄바꿈, 코멘트을 달아줌.
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/mydb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=mysql123

# logging
logging.level.org.hibernate.type.description.sql.BasicBinder=trace
logging.level.org.hibernate.SQL=debug
# Hibernate 6.1.5 updated in springboot 3.x, 4.x
logging.level.org.hibernate.orm.jdbc.bind=trace